### PR TITLE
Gauge creation

### LINKED ISSUE #73: Dial UI to show survey scores after completion
### Problem

We want to show the user their result in the form of a dial on the completion page, once they submit a survey. We do not have such a UI component right now.

### Solution

Please create a dial UI component. Ideally colored green for score of 0 (=good) transitioning to yellow to red for MAX_SCORE  (=bad). This MAX_SCORE is different for each survey - so it should be customizable.

Would look something like this (only 1 dial), indicating how they're doing based on the survey answer:

image

For now, the UI should component should take in:
- MIN_SCORE
- MAX_SCORE
- USER_SCORE

*You do NOT need to try to integrate it with the surveys yet. Put an instance of the component at the bottom of the trends page so we can preview for now.

### Additional context

I found this a while back: https://medium.com/devtechie/new-in-swiftui-4-gauge-view-f76f22be325b

Maybe it could help?

You could also definitely important a static image and use that to do the color gradient part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by emmyxth**
# *Name of the PR*
Creation of gauge component

## :recycle: Current situation & Problem
*Describe the current situation (if possible, with an exemplary (or real) code snippet and/or where this is used)*
*Please link any open issue that is addressed with this PR*
Didn't have health gauge before, will be used after survey completion/in trends page!

## :bulb: Proposed solution
*Describe the solution and how this affects the project and internal structure*
Created gauge component to be integrated with the surveys. Currently has maxValue, minValue, userValue variables that can be used for further iterations. Adapted code from this repository: [https://github.com/honkmaster/TTGaugeView](https://github.com/honkmaster/TTGaugeView)

## :gear: Release Notes 
*Add a summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented if it appends or changes the public interface.*
Currently what it looks like:

UserValue 100 (min: 50, max: 160)
Screenshot 2566-03-06 at 17 42 48

UserValue 50 (min: 50, max: 160)
Screenshot 2566-03-06 at 17 59 34

UserValue 160 (min: 50, max: 160)
Screenshot 2566-03-06 at 17 46 53

## :heavy_plus_sign: Additional Information
*Provide some additional information if possible*

### Related PRs
*Reference the related PRs*

### Testing
*Are there tests included? If yes, which situations are tested, and which corner cases are missing?*
No
### Reviewer Nudging
*Where should the reviewer start? Where is a good entry point?*

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [x ] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jenlmoore** [comment]
Can you please post a screenshot of your changes?

**Comment by jenlmoore** [comment]
I also don't see any changes to the code, except for Jiahui's image, in the files changed section. Can you please make sure all of your changes are shown and are correct

**Comment by jenlmoore** [comment]
Also, we don't want to show the patient a number, rather just where they are on the scale. Please refer to the issue description for more information, which contains this picture as an example:
image

**Comment by emmyxth** [comment]
Sorry, forgot to commit before push! Also, I fixed the gauge to match the spec better. Please see the above screenshot!

**Comment by jenlmoore** [comment]
The tests aren't passing, please look at those again and fix them so they pass, thanks. Until then, please keep this PR as a draft as it is not ready

**Comment by jenlmoore** [comment]
Can you please also show screenshots for differnt scores? Ie. Show what it looks like when a user gets a 1/20 vs. a 10/20 vs. a 15/20 vs. a 20/20, etc. so that we know the functionality works.

**Review by jenlmoore — APPROVED** [review]
lgtm, thanks for getting this in emmy!

**Pull request merged**
