### PR TITLE
Updates schedule to add ResearchKit tasks and set up notifications

### PR DESCRIPTION
**Pull request by vishnuravi**
# Updates schedule to add ResearchKit tasks and set up notifications

## :recycle: Current situation & Problem
The current schedule module cannot launch ResearchKit tasks.

## :bulb: Proposed solution

- Add a ResearchKit Task Context to the schedule to allow it to launch ResearchKit tasks.
- Add notifications to remind users to complete surveys once a month.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vishnuravi** [comment]
@BKrajancich @jenlmoore the schedule is set to display the Edmonton task every day for the time being until the Scheduler issue is fixed in CardinalKit.

**Comment by BKrajancich** [comment]
@vishnuravi do you have any idea why Codecov is failing? Did the settings get changed?

**Review by BKrajancich — APPROVED** [review]
Thank you!!

**Comment by vishnuravi** [comment]
> @vishnuravi do you have any idea why Codecov is failing? Did the settings get changed?

It seems to be a problem across multiple projects. It may be an issue with their API. We are looking into it.

**Pull request merged**
