### PR TITLE
Profile page update

### LINKED ISSUE #20: Add Disease Option to Profile Page
### Problem

We need to show the user what their selected disease is.

### Solution

Add a spot (in replace of the address) for the user's disease to be displayed. 
It should be an editable dropdown with these 3 options:
- Arterial 
- Venous
- I don't know

### Additional context

Please make sure **all** test cases pass AND upload screenshots of your changes!

If you can, please make a branch off of this issue and split it up into as many PRs as possible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### LINKED ISSUE #21: Remove Unnecessary Info from Profile
### Problem

We have too many things in the profile page right now and it doesn't fit our designs.

### Solution

Remove unnecessary information from the profile page so that we are left with only these things:
- First and Last name
- email
- profile image
- disease
- option to change their password

Please look at the figma to design this in the best way

### Additional context

Please make sure **all** test cases pass AND upload screenshots of your changes!

If you can, please make a branch off of this issue and split it up into as many PRs as possible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by jchen23-stf**
# *Name of the PR*
Update profile page 

## :recycle: Current situation & Problem
*Describe the current situation (if possible, with an exemplary (or real) code snippet and/or where this is used)*
- Unnecessary information in profile view 
- Can't edit the data 

*Please link any open issue that is addressed with this PR*

## :bulb: Proposed solution
*Describe the solution and how this affects the project and internal structure*
- Cleaned the information displayed on the UI
- Added edit information functionality 

## :gear: Release Notes 
*Add a summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented if it appends or changes the public interface.*

## :heavy_plus_sign: Additional Information
*Provide some additional information if possible*

### Related PRs
*Reference the related PRs*

### Testing
*Are there tests included? If yes, which situations are tested, and which corner cases are missing?*
- Already tested 

### Reviewer Nudging
*Where should the reviewer start? Where is a good entry point?*

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jchen23-stf** [comment]
image

**Review by jenlmoore — CHANGES_REQUESTED** [review]
Can you please add some tests to hit the code coverage? And add a video of you 'editing' the disease, etc so we can see the functionality? Thanks!

**Comment by jchen23-stf** [comment]
Screen Recording 2023-02-16 at 6.42.02 PM.mov

**Comment by jchen23-stf** [comment]
Screen Recording 2023-02-16 at 6.42.02 PM.mov

**Review by jenlmoore — APPROVED** [review]

**Comment by vishnuravi** [comment]
UI test timed out on Actions, but passed locally. Will bypass branch protection and merge.

**Pull request merged**
