### PR TITLE
Onboarding flow pgs 1,2

### PR DESCRIPTION
**Pull request by BKrajancich**
# Making requested edits from the Utah team, based on our questions

## :recycle: Current situation & Problem
Based on slides 3-4 of this [slide deck](https://docs.google.com/presentation/d/19l1nv36L6qtkm0kGCw9tO5LVnviDO4jMT6GxiWL66vA/edit#slide=id.g21107e4e028_0_9), I made the changes besides the change in font size and the "Streamline your care" request.

It doesn't seem like I'm able to edit anything within CardinalKit, which is where the text specifications are for me to change font size and an external link for "Streamline your care"... does anyone else have this issue too?

## :bulb: Proposed solution
*Describe the solution and how this affects the project and internal structure*

## :heavy_plus_sign: Additional Information
I'm still working on getting some of the features up for the slides, which are listed above.

### Testing
Tests are maintained from the main branch

### Reviewer Nudging
*Where should the reviewer start? Where is a good entry point?*

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by BKrajancich** [comment]
Remaking this PR after it was accidentally merged

**Comment by BKrajancich** [comment]
@ivyalin2015 Let us know when you finish this PR!

**Comment by ivyalin2015** [comment]
Screenshots:
Simulator Screen Shot - iPhone 14 Pro - 2023-02-27 at 18 25 40
Simulator Screen Shot - iPhone 14 Pro - 2023-02-27 at 18 26 01
Simulator Screen Shot - iPhone 14 Pro - 2023-02-27 at 18 26 09
Simulator Screen Shot - iPhone 14 Pro - 2023-02-27 at 18 25 46
Simulator Screen Shot - iPhone 14 Pro - 2023-02-27 at 18 26 16

- Fixed the failing tests (besides the ones on Onboarding page step4)
- increased font size for 1st 3 pages
- edited sign in/login page's text

**Comment by ivyalin2015** [comment]
Simulator Screen Shot - iPhone 14 Pro - 2023-02-28 at 23 58 35
Simulator Screen Shot - iPhone 14 Pro - 2023-02-28 at 23 59 00
Simulator Screen Shot - iPhone 14 Pro - 2023-02-28 at 23 59 07

Fonts increased for main homepage. The only thing I added from onboarding was the consent page, since there was weird spacing, and half of the document was missing for some reason. Meeting with Vishnu and Paul to resolve the text sizing in the questionnaire since they're researchkit controller views and I couldn't figure them out (wasn't able to catch them after class today).

**Comment by BKrajancich** [comment]
Looks good @ivyalin2015! Don't forget the merge conflicts :)

**Comment by BKrajancich** [comment]
Cherry picked changes in #86

**Pull request closed without merging**
