### PR TITLE
Building off of surveyHistoryFinal

### PR DESCRIPTION
**Pull request by ivyalin2015**
# *Create Survey History*

## :recycle: Current situation & Problem
UI not finalized for the questionnaire history section

## :bulb: Proposed solution
Fixed background of the surveyhistory page to be consistent with the rest of the app; added score description for the individual questionnaires

## :gear: Release Notes 
copied the surveyHistoryFinal branch b/c was a detached head - this is the most updated version of that branch!

## :heavy_plus_sign: Additional Information
refer to this branch instead of the surveyHistoryFinal and all branches with similar names - they are now outdated

### Related PRs
surveyHistoryFinal, etc.

### Testing
*Are there tests included? If yes, which situations are tested, and which corner cases are missing?*

### Reviewer Nudging
Simulator Screen Shot - iPhone 14 Pro - 2023-03-15 at 18 00 49
Simulator Screen Shot - iPhone 14 Pro - 2023-03-15 at 18 00 36
Simulator Screen Shot - iPhone 14 Pro - 2023-03-15 at 18 00 59

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jenlmoore** [comment]
Can you please update the branch with main (switch to the main branch and 'pull' from it, then switch back to yours and update it from main)? Thanks!

Also, if the other PRs you have open are outdated, can you please close them? I don't want to do it incorrectly on accident

**Comment by jenlmoore** [comment]
You can run 'swiftlint --fix' in your terminal and it can get rid of some of the issues automatically, although there might be more you have to manually fix

**Comment by ivyalin2015** [comment]
let me know if everything worked!

**Comment by jenlmoore** [comment]
UI and code looks awesome!! Great job!!!

**Comment by jenlmoore** [comment]
Just waiting for tests to finish, then will approve and merge!

**Review by jenlmoore — APPROVED** [review]
Looks great! Fabulous!

**Pull request merged**
