### PR TITLE
Jiahui/profile softlaunch

### LINKED ISSUE #62: Profile Page UI Update
### Problem

The UI of the profile page is not consistent with the rest of the app. 

### Solution

Match the following designs.

This includes:
- background color
- font size
- font style
- font colors
- button style/size
- button colors
- display of fields

Group 2

Also add the LOGOUT button!!
Also in the Figma: https://www.figma.com/file/szFlVU5e8nV7iRHKK9U93F/Untitled?node-id=0%3A1&t=WYnt2IT3xCxmbWbZ-1

### Additional context

Note that we are removing the ability to switch profile pics for the soft launch (as we haven't figure out firebase for this yet). Please keep it in the code as we may bring it back later.

Please have this done by Tuesday.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by jchen23-stf**
# *Name of the PR*
Profile Page Revision for Soft Launch

## :recycle: Current situation & Problem
*Describe the current situation (if possible, with an exemplary (or real) code snippet and/or where this is used)*
*Please link any open issue that is addressed with this PR*

## :bulb: Proposed solution
*Describe the solution and how this affects the project and internal structure*
I changed the profile view UI to fit the figma design 

## :gear: Release Notes 
*Add a summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented if it appends or changes the public interface.*

## :heavy_plus_sign: Additional Information
*Provide some additional information if possible*

### Related PRs
*Reference the related PRs*

### Testing
*Are there tests included? If yes, which situations are tested, and which corner cases are missing?*

### Reviewer Nudging
*Where should the reviewer start? Where is a good entry point?*

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jchen23-stf** [comment]
image

**Comment by BKrajancich** [comment]
@jchen23-stf Thanks for doing this so quickly! Can you also add screenshots for the 2 other pages in #62, the edit condition and help pages?

**Comment by jchen23-stf** [comment]
Of course!
image

image

**Comment by jenlmoore** [comment]
This looks great Jiahui!! One request: can you please make the font larger in both the static texts and the selectors. To an extent where you would likely think its too large 😂 (for older folks sake). Again great job!

**Review by jenlmoore — DISMISSED** [review]
Just the one comment, then will get this in! Thanks!

**Comment by BKrajancich** [comment]
@jchen23-stf looks like the profile UI tests are failing. Do they work locally?

**Comment by BKrajancich** [comment]
@jchen23-stf Can you add a few more UI tests so codecov will pass?

**Review by BKrajancich — APPROVED** [review]

**Pull request merged**
