### PR TITLE
Migrate project to Spezi

### PR DESCRIPTION
**Pull request by vishnuravi**
# Migrate project to Spezi

## :recycle: Current situation & Problem
The project is currently using the January 2023 version of CardinalKit.

## :bulb: Proposed solution
Migrates the project to the new Spezi structure.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by PSchmiedmayer — APPROVED** [review]
Looks great, thank you for migrating it to the latest version of Spezi @vishnuravi 🚀

**Comment by vishnuravi** [comment]
All tests are passing locally, as seen in the screenshot below - tested with a reset simulator and Firebase emulator. I am not sure why the trend test is failing on Github actions. 

Screenshot 2023-06-11 at 4 10 45 PM

**Comment by vishnuravi** [comment]
@PSchmiedmayer  The tests are all passing locally. After reviewing the result from the Github action, I noticed this error occurring before the test fails:

Screenshot 2023-06-11 at 8 25 34 PM

There is a similar issue noted on StackOverflow: https://stackoverflow.com/questions/72702642/github-ci-uitest-gives-flaky-tests-unable-to-monitor-event-loop

Could this be a Github Actions issue unrelated to our project?

**Comment by vishnuravi** [comment]
As @PSchmiedmayer and I discussed, the trends UI test has been disabled since it passes locally, but does not pass on Github actions for an unclear reason. A separate issue will be made to track this.

**Pull request merged**
